package pojo;
// Generated Apr 12, 2018 11:27:14 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Bangdiemdanh generated by hbm2java
 */
@Entity
@Table(name="bangdiemdanh"
    ,catalog="diemdanh"
)
public class Bangdiemdanh  implements java.io.Serializable {


     private BangdiemdanhId id;
     private Monhoc monhoc;
     private Sinhvien sinhvien;
     private String tuanCoMat;
     private String tuanVangMat;
     private String tenSinhVien;

    public Bangdiemdanh() {
    }

	
    public Bangdiemdanh(BangdiemdanhId id, Monhoc monhoc, Sinhvien sinhvien) {
        this.id = id;
        this.monhoc = monhoc;
        this.sinhvien = sinhvien;
    }
    public Bangdiemdanh(BangdiemdanhId id, Monhoc monhoc, Sinhvien sinhvien, String tuanCoMat, String tuanVangMat, String tenSinhVien) {
       this.id = id;
       this.monhoc = monhoc;
       this.sinhvien = sinhvien;
       this.tuanCoMat = tuanCoMat;
       this.tuanVangMat = tuanVangMat;
       this.tenSinhVien = tenSinhVien;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="maMh", column=@Column(name="MaMH", nullable=false, length=10) ), 
        @AttributeOverride(name="mssv", column=@Column(name="MSSV", nullable=false, length=10) ) } )
    public BangdiemdanhId getId() {
        return this.id;
    }
    
    public void setId(BangdiemdanhId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaMH", nullable=false, insertable=false, updatable=false)
    public Monhoc getMonhoc() {
        return this.monhoc;
    }
    
    public void setMonhoc(Monhoc monhoc) {
        this.monhoc = monhoc;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MSSV", nullable=false, insertable=false, updatable=false)
    public Sinhvien getSinhvien() {
        return this.sinhvien;
    }
    
    public void setSinhvien(Sinhvien sinhvien) {
        this.sinhvien = sinhvien;
    }

    
    @Column(name="TuanCoMat", length=50)
    public String getTuanCoMat() {
        return this.tuanCoMat;
    }
    
    public void setTuanCoMat(String tuanCoMat) {
        this.tuanCoMat = tuanCoMat;
    }

    
    @Column(name="TuanVangMat", length=50)
    public String getTuanVangMat() {
        return this.tuanVangMat;
    }
    
    public void setTuanVangMat(String tuanVangMat) {
        this.tuanVangMat = tuanVangMat;
    }

    
    @Column(name="TenSinhVien", length=45)
    public String getTenSinhVien() {
        return this.tenSinhVien;
    }
    
    public void setTenSinhVien(String tenSinhVien) {
        this.tenSinhVien = tenSinhVien;
    }




}


