package pojo;
// Generated Apr 12, 2018 11:27:14 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BangdiemdanhId generated by hbm2java
 */
@Embeddable
public class BangdiemdanhId  implements java.io.Serializable {


     private String maMh;
     private String mssv;

    public BangdiemdanhId() {
    }

    public BangdiemdanhId(String maMh, String mssv) {
       this.maMh = maMh;
       this.mssv = mssv;
    }

    @Column(name="MaMH", nullable=false, length=10)
    public String getMaMh() {
        return this.maMh;
    }
    
    public void setMaMh(String maMh) {
        this.maMh = maMh;
    }


    @Column(name="MSSV", nullable=false, length=10)
    public String getMssv() {
        return this.mssv;
    }
    
    public void setMssv(String mssv) {
        this.mssv = mssv;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BangdiemdanhId) ) return false;
		 BangdiemdanhId castOther = ( BangdiemdanhId ) other; 
         
		 return ( (this.getMaMh()==castOther.getMaMh()) || ( this.getMaMh()!=null && castOther.getMaMh()!=null && this.getMaMh().equals(castOther.getMaMh()) ) )
 && ( (this.getMssv()==castOther.getMssv()) || ( this.getMssv()!=null && castOther.getMssv()!=null && this.getMssv().equals(castOther.getMssv()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMaMh() == null ? 0 : this.getMaMh().hashCode() );
         result = 37 * result + ( getMssv() == null ? 0 : this.getMssv().hashCode() );
         return result;
   }   


}


