package pojo;
// Generated Apr 12, 2018 11:27:14 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Giaovu generated by hbm2java
 */
@Entity
@Table(name="giaovu"
    ,catalog="diemdanh"
)
public class Giaovu  implements java.io.Serializable {


     private String maGv;
     private String tenGv;
     private String password;
     private String tenDangNhap;
     private Set<Monhoc> monhocs = new HashSet<Monhoc>(0);

    public Giaovu() {
    }

	
    public Giaovu(String maGv) {
        this.maGv = maGv;
    }
    public Giaovu(String maGv, String tenGv, String password, String tenDangNhap, Set<Monhoc> monhocs) {
       this.maGv = maGv;
       this.tenGv = tenGv;
       this.password = password;
       this.tenDangNhap = tenDangNhap;
       this.monhocs = monhocs;
    }
   
     @Id 

    
    @Column(name="MaGV", unique=true, nullable=false, length=10)
    public String getMaGv() {
        return this.maGv;
    }
    
    public void setMaGv(String maGv) {
        this.maGv = maGv;
    }

    
    @Column(name="TenGV", length=45)
    public String getTenGv() {
        return this.tenGv;
    }
    
    public void setTenGv(String tenGv) {
        this.tenGv = tenGv;
    }

    
    @Column(name="Password", length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="TenDangNhap", length=45)
    public String getTenDangNhap() {
        return this.tenDangNhap;
    }
    
    public void setTenDangNhap(String tenDangNhap) {
        this.tenDangNhap = tenDangNhap;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="giaovu")
    public Set<Monhoc> getMonhocs() {
        return this.monhocs;
    }
    
    public void setMonhocs(Set<Monhoc> monhocs) {
        this.monhocs = monhocs;
    }




}


