package pojo;
// Generated Apr 12, 2018 11:27:14 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Monhoc generated by hbm2java
 */
@Entity
@Table(name="monhoc"
    ,catalog="diemdanh"
)
public class Monhoc  implements java.io.Serializable {


     private String maMh;
     private Giaovu giaovu;
     private String tenMh;
     private Set<Bangdiemdanh> bangdiemdanhs = new HashSet<Bangdiemdanh>(0);
     private Set<Thoikhoabieu> thoikhoabieus = new HashSet<Thoikhoabieu>(0);

    public Monhoc() {
    }

    public Monhoc(String maMh, Giaovu giaovu, String tenMh) {
        this.maMh = maMh;
        this.giaovu = giaovu;
        this.tenMh = tenMh;
    }

	
    public Monhoc(String maMh) {
        this.maMh = maMh;
    }
    public Monhoc(String maMh, Giaovu giaovu, String tenMh, Set<Bangdiemdanh> bangdiemdanhs, Set<Thoikhoabieu> thoikhoabieus) {
       this.maMh = maMh;
       this.giaovu = giaovu;
       this.tenMh = tenMh;
       this.bangdiemdanhs = bangdiemdanhs;
       this.thoikhoabieus = thoikhoabieus;
    }
   
     @Id 

    
    @Column(name="MaMH", unique=true, nullable=false, length=10)
    public String getMaMh() {
        return this.maMh;
    }
    
    public void setMaMh(String maMh) {
        this.maMh = maMh;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaGV")
    public Giaovu getGiaovu() {
        return this.giaovu;
    }
    
    public void setGiaovu(Giaovu giaovu) {
        this.giaovu = giaovu;
    }

    
    @Column(name="TenMH", length=45)
    public String getTenMh() {
        return this.tenMh;
    }
    
    public void setTenMh(String tenMh) {
        this.tenMh = tenMh;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="monhoc")
    public Set<Bangdiemdanh> getBangdiemdanhs() {
        return this.bangdiemdanhs;
    }
    
    public void setBangdiemdanhs(Set<Bangdiemdanh> bangdiemdanhs) {
        this.bangdiemdanhs = bangdiemdanhs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="monhoc")
    public Set<Thoikhoabieu> getThoikhoabieus() {
        return this.thoikhoabieus;
    }
    
    public void setThoikhoabieus(Set<Thoikhoabieu> thoikhoabieus) {
        this.thoikhoabieus = thoikhoabieus;
    }




}


