package pojo;
// Generated Apr 12, 2018 11:27:14 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sinhvien generated by hbm2java
 */
@Entity
@Table(name = "sinhvien",
         catalog = "diemdanh"
)
public class Sinhvien implements java.io.Serializable {

    private String mssv;
    private String tenSv;
    private String password;
    private Set<Bangdiemdanh> bangdiemdanhs = new HashSet<Bangdiemdanh>(0);

    public Sinhvien(String mssv, String password) {
        this.mssv = mssv;
        this.password = password;
    }


    public Sinhvien() {
    }

    public Sinhvien(String mssv) {
        this.mssv = mssv;
    }

    public Sinhvien(String mssv, String tenSv, String password, Set<Bangdiemdanh> bangdiemdanhs) {
        this.mssv = mssv;
        this.tenSv = tenSv;
        this.password = password;
        this.bangdiemdanhs = bangdiemdanhs;
    }

    @Id

    @Column(name = "MSSV", unique = true, nullable = false, length = 10)
    public String getMssv() {
        return this.mssv;
    }

    public void setMssv(String mssv) {
        this.mssv = mssv;
    }

    @Column(name = "TenSV", length = 45)
    public String getTenSv() {
        return this.tenSv;
    }

    public void setTenSv(String tenSv) {
        this.tenSv = tenSv;
    }

    @Column(name = "Password", length = 45)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "sinhvien")
    public Set<Bangdiemdanh> getBangdiemdanhs() {
        return this.bangdiemdanhs;
    }

    public void setBangdiemdanhs(Set<Bangdiemdanh> bangdiemdanhs) {
        this.bangdiemdanhs = bangdiemdanhs;
    }

}
