/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainFrame;

import DAO.BangDiemDanhDAO;
import DAO.GiaoVuDAO;
import DAO.HashDAO;
import DAO.MonHocDAO;
import DAO.SinhVienDAO;
import DAO.ThoiKhoaBieuDAO;
import java.awt.HeadlessException;
import java.sql.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import pojo.Bangdiemdanh;
import pojo.BangdiemdanhId;
import pojo.Giaovu;
import pojo.Monhoc;
import pojo.Sinhvien;
import pojo.Thoikhoabieu;
import pojo.ThoikhoabieuId;

/**
 *
 * @author Gokki
 */
public class JGiaoVu extends javax.swing.JFrame {

    /**
     * Creates new form JGiaoVu
     *
     * @throws java.lang.ClassNotFoundException
     */
    private static Giaovu giaovu = null;
    private static Date NKT = null;
    private static Date NBD = null;

    private static DefaultComboBoxModel dcm = null;
    private static DefaultComboBoxModel dcm2 = null;
    private static DefaultComboBoxModel dcm3 = null;

    private static DefaultTableModel dtm = null;
    private static DefaultTableModel dtm2 = null;

    private static List<Sinhvien> list_sv = null;

    private static int index_of_CMH2 = -1;
    private static int index_of_CMH3 = -1;

    public JGiaoVu(Giaovu gv) throws ClassNotFoundException {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(JGiaoVu.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        giaovu = gv;
        setLocationRelativeTo(null);
        btnTaoMonHoc.requestFocus(true);
        tbxMaGV.setText(giaovu.getMaGv());
        tbxHoVaTenGV.setText(giaovu.getTenGv());

        LoadDSMonHoc();

        cbxChonMonHoc1.setModel(dcm);
        cbxChonMonHoc1.setSelectedIndex(-1);

        cbxCMH2.setModel(dcm2);
        cbxCMH2.setSelectedIndex(-1);

        cbxCMH3.setModel(dcm3);
        cbxCMH3.setSelectedIndex(-1);

        dtm = (DefaultTableModel) tbldssv.getModel();
        dtm2 = (DefaultTableModel) tblDiemDanh.getModel();
        LoadDssvIntoTable();
//        tbldssv.setModel(dtm);
//        tbldssv.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tbxMaMonHoc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tbxTenMonHoc = new javax.swing.JTextField();
        btnTaoMonHoc = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        cbxChonMonHoc1 = new javax.swing.JComboBox<>();
        tbxdisplayMH = new javax.swing.JTextField();
        btnXemMH = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbxDay = new javax.swing.JComboBox<>();
        cbxMonth = new javax.swing.JComboBox<>();
        tbxYear = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tbxNgayKetThuc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tbxThuTrongTuan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tbxPhongHoc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        spnGBD = new javax.swing.JSpinner();
        spnPBD = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        spnGKT = new javax.swing.JSpinner();
        jLabel25 = new javax.swing.JLabel();
        spnPKT = new javax.swing.JSpinner();
        jPanel9 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        btnDoiMatKhau = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        tbxMaGV = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tbxHoVaTenGV = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        cbxCMH2 = new javax.swing.JComboBox<>();
        tbxdisplayMH2 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldssv = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        tbxAddMSSV = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tbxAddHoTenSV = new javax.swing.JTextField();
        btnXacNhanAddSingle = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDiemDanh = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        cbxCMH3 = new javax.swing.JComboBox<>();
        btnXacNhanThayDoi = new javax.swing.JButton();
        tbxdisplayMonHoc3 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setTitle("Chuong Trinh Diem Danh");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Tạo Môn Học", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Mã Môn Học");

        tbxMaMonHoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tên Môn Học");

        tbxTenMonHoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnTaoMonHoc.setBackground(new java.awt.Color(0, 0, 255));
        btnTaoMonHoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTaoMonHoc.setForeground(new java.awt.Color(0, 0, 255));
        btnTaoMonHoc.setText("Tạo Môn Học");
        btnTaoMonHoc.setToolTipText("");
        btnTaoMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoMonHocActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Xem Môn Học");

        cbxChonMonHoc1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxChonMonHoc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxChonMonHoc1ActionPerformed(evt);
            }
        });

        tbxdisplayMH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnXemMH.setText("Xem");
        btnXemMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemMHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tbxMaMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tbxTenMonHoc)))
                            .addComponent(btnTaoMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 36, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxChonMonHoc1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tbxdisplayMH))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnXemMH)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cbxChonMonHoc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxdisplayMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXemMH)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tbxMaMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tbxTenMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(btnTaoMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Thời Khóa Biểu ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Ngày Bắt Đầu");

        cbxDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbxDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDayActionPerformed(evt);
            }
        });

        cbxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("<html>\n( Ngày Kết thúc là 15 tuần <br>\nsau kể từ ngày bắt đầu)\n\n</html>"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Ngày Kết Thúc");

        tbxNgayKetThuc.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Thứ Trong Tuần");

        tbxThuTrongTuan.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Giờ Bắt Đầu");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Giờ Kết Thúc");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Tên Phòng Học");

        jLabel10.setText("day");

        jLabel11.setText("month");

        jLabel12.setText("year (yyyy)");

        jButton5.setBackground(new java.awt.Color(0, 0, 255));
        jButton5.setForeground(new java.awt.Color(0, 0, 255));
        jButton5.setText("Xác Nhận");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        spnGBD.setModel(new javax.swing.SpinnerNumberModel(7, 0, 23, 1));

        spnPBD.setModel(new javax.swing.SpinnerNumberModel(30, 0, 60, 5));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Giờ");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Phút");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Giờ");

        spnGKT.setModel(new javax.swing.SpinnerNumberModel(9, 0, 23, 1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Phút");

        spnPKT.setModel(new javax.swing.SpinnerNumberModel(30, 0, 60, 5));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(cbxDay, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tbxYear))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tbxPhongHoc, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnGKT, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnPKT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnGBD, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnPBD, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tbxThuTrongTuan))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tbxNgayKetThuc)))
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(tbxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tbxNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tbxThuTrongTuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(spnGBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnPBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spnGKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spnPKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24)
                        .addComponent(jLabel25))
                    .addComponent(jLabel8))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tbxPhongHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        btnLogout.setBackground(new java.awt.Color(0, 0, 255));
        btnLogout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(0, 0, 255));
        btnLogout.setText("Đăng Xuất");
        btnLogout.setToolTipText("");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnDoiMatKhau.setBackground(new java.awt.Color(0, 0, 255));
        btnDoiMatKhau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDoiMatKhau.setForeground(new java.awt.Color(0, 0, 255));
        btnDoiMatKhau.setText("Đổi Mật Khẩu");
        btnDoiMatKhau.setToolTipText("");
        btnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMatKhauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDoiMatKhau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1101, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Tài Khoản Đăng Nhập", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Mã Giáo Viên");

        tbxMaGV.setEditable(false);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Họ và Tên");

        tbxHoVaTenGV.setEditable(false);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tbxMaGV, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tbxHoVaTenGV, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tbxMaGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(tbxHoVaTenGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Tạo Môn Học", jPanel2);

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Chọn Môn Học", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Chọn Môn Học");

        cbxCMH2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxCMH2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCMH2ActionPerformed(evt);
            }
        });

        tbxdisplayMH2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbxCMH2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(tbxdisplayMH2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cbxCMH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxdisplayMH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Thêm Từ Danh Sách", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        tbldssv.setBackground(new java.awt.Color(204, 204, 255));
        tbldssv.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        tbldssv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbldssv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "MSSV", "Họ Và Tên", "Chọn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbldssv);
        if (tbldssv.getColumnModel().getColumnCount() > 0) {
            tbldssv.getColumnModel().getColumn(0).setPreferredWidth(5);
            tbldssv.getColumnModel().getColumn(1).setPreferredWidth(15);
            tbldssv.getColumnModel().getColumn(3).setPreferredWidth(10);
        }

        jButton1.setBackground(new java.awt.Color(0, 51, 255));
        jButton1.setText("Xác Nhận");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Thêm Sinh Viên Mới", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("MSSV");

        tbxAddMSSV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Họ Và Tên");

        tbxAddHoTenSV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnXacNhanAddSingle.setBackground(new java.awt.Color(0, 51, 255));
        btnXacNhanAddSingle.setText("Xác Nhận");
        btnXacNhanAddSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanAddSingleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(tbxAddMSSV))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbxAddHoTenSV))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnXacNhanAddSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tbxAddMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tbxAddHoTenSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btnXacNhanAddSingle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Import Dữ Liệu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1412333", "Dương Thiết Tâm"},
                {"1512477", "Trương Vô Kỵ"}
            },
            new String [] {
                "MSSV", "Họ Và Tên"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel16.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 51, 51));
        jLabel16.setText("<html>\nGiáo viên tạo file có đuôi .csv theo mẫu sau <br>và import vào chương trình\n\n</html>");

        jButton3.setBackground(new java.awt.Color(0, 0, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Import");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Thêm Sinh Viên Vào Môn Học", jPanel4);

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));

        tblDiemDanh.setBackground(new java.awt.Color(204, 204, 255));
        tblDiemDanh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblDiemDanh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MSSV", "Họ Và Tên", "T 1", "T 2", "T 3", "T 4", "T 5", "T 6", "T 7", "T 8", "T 9", "T 10", "T 11", "T 12", "T 13", "T 14", "T 15"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblDiemDanh);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Chọn Môn Học");

        cbxCMH3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxCMH3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCMH3ActionPerformed(evt);
            }
        });

        btnXacNhanThayDoi.setBackground(new java.awt.Color(51, 51, 255));
        btnXacNhanThayDoi.setText("Xác Nhận Thay Đổi");
        btnXacNhanThayDoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanThayDoiActionPerformed(evt);
            }
        });

        tbxdisplayMonHoc3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxCMH3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tbxdisplayMonHoc3, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                .addComponent(btnXacNhanThayDoi, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXacNhanThayDoi, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(cbxCMH3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(tbxdisplayMonHoc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Xem Kết Quả Điểm Danh", jPanel7);

        jMenu1.setText("Help");

        jMenuItem1.setText("Help");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private static long index = 1;

    public static void LoadDssvIntoTable() {
        try {
            list_sv = SinhVienDAO.getListSinhVien(); // lấy ra dssv
            if (list_sv != null) {  // nếu danh sách tồn tại thì load lên table
                list_sv.stream().map((s) -> {
                    dtm.addRow(new Object[]{
                        index, s.getMssv(), s.getTenSv(), false
                    });
                    return s;
                }).forEachOrdered((_item) -> {
                    index++;
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
            return;
        }

    }

    public static void LoadDSMonHoc() {
        List<Monhoc> ds = MonHocDAO.GetListMonHoc();
        dcm = new DefaultComboBoxModel();
        dcm2 = new DefaultComboBoxModel();
        dcm3 = new DefaultComboBoxModel();
        if (ds != null) {
            ds.stream().map((d) -> {
                dcm.addElement(d.getMaMh());
                return d;
            }).map((d) -> {
                dcm2.addElement(d.getMaMh());
                return d;
            }).forEachOrdered((d) -> {
                dcm3.addElement(d.getMaMh());
            });

        }

    }

    private void cbxDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDayActionPerformed

    }//GEN-LAST:event_cbxDayActionPerformed

    private void btnTaoMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoMonHocActionPerformed
        // kiểm tra có nội dung chưa được điền
        if (tbxMaMonHoc.getText().isEmpty() || tbxTenMonHoc.getText().isEmpty()
                || tbxYear.getText().isEmpty() || tbxPhongHoc.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin môn học và thời khóa biểu");
            return;
        } else { // đã điền đầy đủ thông tin
            if (tbxNgayKetThuc.getText().isEmpty()) { // chưa generate ngày kết thúc môn
                JOptionPane.showMessageDialog(this, "Vui lòng bấm xác nhận để lấy ngày kết thúc môn học");
                return;
            } else {
                Monhoc mh = MonHocDAO.getMonHocByMaMH(tbxMaMonHoc.getText()); // xem môn học đã tồn tại chưa
                if (mh == null) { // chưa tồn tại, sẽ tạo mới
                    mh = new Monhoc(tbxMaMonHoc.getText(), giaovu, tbxTenMonHoc.getText()); //tạo môn học mới từ mã,giáo vụ, tên mh
                    ThoikhoabieuId tkbid = new ThoikhoabieuId(tbxMaMonHoc.getText(), tbxTenMonHoc.getText());
                    String gioBatDau = String.valueOf(spnGBD.getValue()) + ":" + String.valueOf(spnPBD.getValue());
                    String gioKetThuc = String.valueOf(spnGKT.getValue()) + ":" + String.valueOf(spnPKT.getValue());
                    Thoikhoabieu tkb = new Thoikhoabieu(tkbid, mh, NBD, NKT, tbxThuTrongTuan.getText(), gioBatDau, gioKetThuc, tbxPhongHoc.getText());

                    String confirm = "Xác nhận tạo môn học: \r\n Mã môn học:" + mh.getMaMh()
                            + "\r\n " + mh.getTenMh()
                            + "\r\n Ngày bắt đầu:"
                            + NBD + "\r\n Ngày kết thúc: " + NKT + "\r\n " + tkb.getThuTrongTuan()
                            + "\r\n Giờ bắt đầu: "
                            + tkb.getGioBatDau() + "\r\n Giờ kết thúc: " + tkb.getGioKetThuc()
                            + "\r\n Phòng " + tkb.getTenPhongHoc();
                    int chon = JOptionPane.showConfirmDialog(this, confirm);
                    if (chon != JOptionPane.OK_OPTION) {
                        return;
                    }
                    boolean kq = MonHocDAO.SaveMonHoc(mh);
                    kq = ThoiKhoaBieuDAO.SaveThoiKhoaBieu(tkb);
                    if (kq) {
                        JOptionPane.showMessageDialog(this, "Tạo môn học thành công");
                        LoadDSMonHoc();

                        cbxChonMonHoc1.setModel(dcm);
                        cbxChonMonHoc1.repaint();

                        cbxCMH2.setModel(dcm2);
                        cbxCMH2.repaint();

                        cbxCMH3.setModel(dcm3);
                        cbxCMH3.repaint();
                        return;
                    } else {
                        JOptionPane.showMessageDialog(this, "Có lỗi trong quá trình tạo môn học");
                    }
                } else { // mã môn học đã tồn tại
                    JOptionPane.showMessageDialog(this, "Mã môn học này đã tồn tại. Vui lòng kiểm tra lại.");
                    return;
                }
            }
        }
    }//GEN-LAST:event_btnTaoMonHocActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.setVisible(false);
        try {
            JLogin jjj = new JLogin();
            jjj.setVisible(true);
            jjj.show(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JGiaoVu.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMatKhauActionPerformed
        String mkc = giaovu.getPassword();
        DlgChangePassGiaoVu dlg = new DlgChangePassGiaoVu(this, true, giaovu);
        dlg.setVisible(true);
        if (mkc.compareTo(giaovu.getPassword()) == 0) {
            return;
        }
        giaovu.setPassword(HashDAO.encryp(giaovu.getPassword(), 3));
        boolean kq = GiaoVuDAO.UpdateGiaoVu(giaovu);
        if (kq) {
            JOptionPane.showMessageDialog(this, "Cập nhật mật khẩu thành công");
            return;
        } else {
            JOptionPane.showMessageDialog(this, "Xảy ra lỗi. Cập nhật mật khẩu thất bại.");
            return;
        }
    }//GEN-LAST:event_btnDoiMatKhauActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        JLogin jlg;
        try {
            jlg = new JLogin();
            jlg.setVisible(true);
            jlg.show(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JGiaoVu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        DlgGiaoVuHelp dlg = new DlgGiaoVuHelp(this, true);
        dlg.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public static long getTimeFor(int so_tuan) {
        return (so_tuan * 7 * 24 * 60 * 60 * 60 * 60);
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int ngay = Integer.parseInt((String) cbxDay.getSelectedItem());
        int thang = Integer.parseInt((String) cbxMonth.getSelectedItem());
        long daytime = TimeUnit.DAYS.toMillis(15 * 7); // tính bao nhiêu ngày
        try {
            int nam = Integer.parseInt(tbxYear.getText());
            NBD = new Date(nam - 1900, thang - 1, ngay);
            NKT = new Date(NBD.getTime() + daytime);
            tbxNgayKetThuc.setText(NKT.toString());
            if ((NBD.getDay() + 1) == 1) {
                tbxThuTrongTuan.setText("Chủ Nhật");
            } else {
                tbxThuTrongTuan.setText("Thứ " + (NBD.getDay() + 1));

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Năm bắt đầu chưa đúng định dạng. Xin kiểm tra lại");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void cbxChonMonHoc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxChonMonHoc1ActionPerformed
        if (cbxChonMonHoc1.getSelectedIndex() != -1) { // nếu chọn mã số môn học thích hợp
            Monhoc mh = MonHocDAO.getMonHocByMaMH(cbxChonMonHoc1.getItemAt(cbxChonMonHoc1.getSelectedIndex()));
            ThoikhoabieuId tkbid = new ThoikhoabieuId(mh.getMaMh(), mh.getTenMh());
            tbxdisplayMH.setText(mh.getTenMh());
        }
    }//GEN-LAST:event_cbxChonMonHoc1ActionPerformed

    private void cbxCMH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCMH2ActionPerformed
        if (cbxCMH2.getSelectedIndex() != -1) {

            if (index_of_CMH2 != cbxCMH2.getSelectedIndex()) { // nếu chọn một môn học khác
                index_of_CMH2 = cbxCMH2.getSelectedIndex(); // set chỉ mục bằng chỉ mục đang chọn

                Dlgloading dlgl = new Dlgloading(this, true);
                dlgl.setModal(true);

                Thread t = new Thread() {
                    public void run() {
                        String mmh = (String) cbxCMH2.getSelectedItem();
                        Monhoc mh = MonHocDAO.getMonHocByMaMH(mmh);
                        tbxdisplayMH2.setText(mh.getTenMh()); // set textbox tên môn học
                        int rows = dtm.getRowCount();
                        BangdiemdanhId bddid = null;
                        for (int i = 0; i < rows; i++) {
                            String mssv = String.valueOf(dtm.getValueAt(i, 1));
                            bddid = new BangdiemdanhId(mh.getMaMh(), mssv);
                            if (BangDiemDanhDAO.getBDDByID(bddid) != null) {
                                dtm.setValueAt(true, i, 3);
                            } else {
                                dtm.setValueAt(false, i, 3);
                            }
                        }
                        SwingUtilities.invokeLater(new Runnable() {//do swing work on EDT
                            public void run() {
                                dlgl.dispose();
                            }
                        });
                    }
                };
                t.start();
                dlgl.setVisible(true);
            }
        }
    }//GEN-LAST:event_cbxCMH2ActionPerformed

    private void btnXemMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemMHActionPerformed
        if (cbxChonMonHoc1.getSelectedIndex() != -1) {
            Monhoc mh = MonHocDAO.getMonHocByMaMH(cbxChonMonHoc1.getItemAt(cbxChonMonHoc1.getSelectedIndex()));
            ThoikhoabieuId tkbid = new ThoikhoabieuId(mh.getMaMh(), mh.getTenMh());
            Thoikhoabieu tkb = ThoiKhoaBieuDAO.GetTKBByTKBId(tkbid);
            String ChiTietMH = "Mã Môn Học: " + mh.getMaMh() + "\r\n"
                    + "Tên Môn Học: " + mh.getTenMh() + "\r\n"
                    + "Ngày Bắt Đầu: " + tkb.getNgayBatDau().toString() + "\r\n"
                    + "Ngày Kết Thúc: " + tkb.getNgayKetThuc().toString() + "\r\n"
                    + "Thứ Trong Tuần: " + tkb.getThuTrongTuan() + "\r\n"
                    + "Giờ Bắt Đầu: " + tkb.getGioBatDau() + "\r\n"
                    + "Giờ Kết Thúc: " + tkb.getGioKetThuc() + "\r\n"
                    + "Phòng Học: " + tkb.getTenPhongHoc() + "\r\n";

            JOptionPane.showMessageDialog(null, ChiTietMH);

        }
    }//GEN-LAST:event_btnXemMHActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String MMH = (String) cbxCMH2.getSelectedItem(); // lấy mã môn học đang muốn thêm
        Monhoc mh = MonHocDAO.getMonHocByMaMH(MMH); // lấy ra môn học đang chọn
        int cf = JOptionPane.showConfirmDialog(this, "Xác nhận thay đổi danh sách sinh viên môn " + mh.getTenMh() + "?");

        if (cf == JOptionPane.OK_OPTION) { // lựa chọn có

            Dlgloading dlgl = new Dlgloading(this, true);
            dlgl.setModal(true);

            Thread t = new Thread() {
                boolean kq = false;

                public void run() {
                    Bangdiemdanh bdd = null;
                    int rows = dtm.getRowCount(); // lấy số dòng trên bảng
                    BangdiemdanhId bddid = null;
                    for (int i = 0; i < rows; i++) {
                        if ((boolean) dtm.getValueAt(i, 3) == false) { // xóa sinh viên dưới dữ liệu
                            String mssv = String.valueOf(dtm.getValueAt(i, 1)); // lấy mssv của sv được chọn
                            bddid = new BangdiemdanhId(MMH, mssv);
                            bdd = new Bangdiemdanh(bddid, mh, new Sinhvien(mssv, (String) dtm.getValueAt(i, 2), null, null), null, null, (String) dtm.getValueAt(i, 2));

                            kq = BangDiemDanhDAO.DeleteBDD(bdd);

                        } else { // thêm sinh viên vào dữ liệu
                            String mssv = String.valueOf(dtm.getValueAt(i, 1)); // lấy mssv của sv được chọn
                            bddid = new BangdiemdanhId(MMH, mssv);
                            bdd = new Bangdiemdanh(bddid, mh, new Sinhvien(mssv, (String) dtm.getValueAt(i, 2), null, null), null, null, (String) dtm.getValueAt(i, 2));

                            kq = BangDiemDanhDAO.SaveBDD(bdd);
                        }
                    }

                    SwingUtilities.invokeLater(new Runnable() {//do swing work on EDT
                        public void run() {
                            dlgl.dispose();
                            if (kq) {
                                JOptionPane.showMessageDialog(null, "Thay đổi thành công");
                            } else {
                                JOptionPane.showMessageDialog(null, "fail");
                            }

                        }
                    });
                }
            };
            t.start();
            dlgl.setVisible(true);

        } else {
            return;
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnXacNhanAddSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanAddSingleActionPerformed
        if (cbxCMH2.getSelectedIndex() != -1) {
            if (tbxAddMSSV.getText().isEmpty() || tbxAddHoTenSV.getText().isEmpty()) {// chưa điển đủ dữ liêu
                JOptionPane.showMessageDialog(this, "Yêu cầu điền đủ MSSV và Họ tên!!");
                return;
            }
            String mssv = tbxAddMSSV.getText(); // lấy ra mssv
            String MaMH = (String) cbxCMH2.getSelectedItem(); // lấy ra mã môn học

            BangdiemdanhId bddid = new BangdiemdanhId(MaMH, mssv); // tạo ID bảng điểm danh từ dữ liệu trên
            if (BangDiemDanhDAO.getBDDByID(bddid) != null) {
                JOptionPane.showMessageDialog(this, "Sinh viên đã có trong danh sách");
                return;
            } else {
                Monhoc mh = MonHocDAO.getMonHocByMaMH(MaMH);
                Sinhvien sv = new Sinhvien(mssv, tbxAddHoTenSV.getText(), null, null);
                SinhVienDAO.SaveNewSinhVien(sv);
                Bangdiemdanh bdd = new Bangdiemdanh(bddid, mh, sv, null, null, sv.getTenSv());
                if (BangDiemDanhDAO.SaveBDD(bdd)) {
                    JOptionPane.showMessageDialog(this, "Thêm thành công");
                    dtm.addRow(new Object[]{
                        index++, mssv, sv.getTenSv(), true
                    });
                }

            }

        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn môn học!");
            return;
        }
    }//GEN-LAST:event_btnXacNhanAddSingleActionPerformed

    public void RefreshDiemDanhtbl() {
        int rows = tblDiemDanh.getRowCount();
        while (rows > 0) {
            dtm2.removeRow(0);
            rows--;
        }
        tblDiemDanh.repaint();
    }
    private void cbxCMH3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCMH3ActionPerformed
        if (cbxCMH3.getSelectedIndex() != -1) {

            if (cbxCMH3.getSelectedIndex() != index_of_CMH3) {
                Dlgloading dlgl = new Dlgloading(this, true);
                dlgl.setModal(true);
                Thread t = new Thread() {
                    public void run() {

                        RefreshDiemDanhtbl();
                        index_of_CMH3 = cbxCMH3.getSelectedIndex();
                        String Mamh = (String) cbxCMH3.getSelectedItem();
                        Monhoc mh = MonHocDAO.getMonHocByMaMH(Mamh);
                        tbxdisplayMonHoc3.setText(mh.getTenMh());

                        Iterator<Bangdiemdanh> bdds = mh.getBangdiemdanhs().iterator(); // lấy ra bảng các xinh viên để điểm danh
                        int dihoc[] = new int[15];
                        int tbDiemDanhIndex = 0;
                        while (bdds.hasNext()) {
                            Bangdiemdanh bdd = bdds.next();
                            String ncm = bdd.getTuanCoMat(); //  lấy chuỗi thể hiện ngày có mặt
                            dtm2.addRow(new Object[]{
                                bdd.getSinhvien().getMssv(), bdd.getTenSinhVien()
                            });
                            if (ncm == null || ncm.isEmpty() || ncm.compareTo("") == 0) {
                                tbDiemDanhIndex++;
                                continue;
                            } else {
                                String s[] = ncm.split(",");
                                for (String st : s) {
                                    dtm2.setValueAt(true, tbDiemDanhIndex, Integer.valueOf(st) + 1);
                                }
                            }
                            tbDiemDanhIndex++;
                        }
                        SwingUtilities.invokeLater(new Runnable() {//do swing work on EDT
                            public void run() {
                                dlgl.dispose();
                            }
                        });
                    }

                };
                t.start();
                dlgl.setVisible(true);
            }

        }
    }//GEN-LAST:event_cbxCMH3ActionPerformed

    private void btnXacNhanThayDoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanThayDoiActionPerformed
        if (cbxCMH3.getSelectedIndex() != -1) {
            Dlgloading d = new Dlgloading(this, true);
            d.setModal(true);
            Thread t = new Thread() {
                public void run() {
                    String Mamh = (String) cbxCMH3.getSelectedItem(); // lấy mã môn học
                    String ncm = "";
                    int rows = tblDiemDanh.getRowCount(); // lấy số dòng của bảng
                    BangdiemdanhId bddid = null; // tạo id cho bảng điểm danh
                    Bangdiemdanh bdd = null; // tạo bảng điểm danh

                    for (int i = 0; i < rows; i++) { // duyệt qua số dòng
                        for (int j = 2; j < 17; j++) { // duyệt qua số cột điểm danh
                            if (dtm2.getValueAt(i, j) != null && (boolean) dtm2.getValueAt(i, j) == true) {
                                ncm = (ncm + String.valueOf(j - 1) + ",");
                            }
                        }
                        bddid = new BangdiemdanhId(Mamh, (String) dtm2.getValueAt(i, 0));
                        try {
                            bdd = BangDiemDanhDAO.getBDDByID(bddid);
                            bdd.setTuanCoMat(ncm);
                            if (BangDiemDanhDAO.UpdateBDD(bdd) == false) {
                                JOptionPane.showMessageDialog(null, "Cập nhật bảng điểm danh thất bại");
                                return;
                            }
                            ncm = "";
                        } catch (HeadlessException e) {
                            JOptionPane.showMessageDialog(null, "Cập nhật bảng điểm danh thất bại");
                        }

                    }
                    SwingUtilities.invokeLater(new Runnable() {//do swing work on EDT
                        public void run() {
                            d.dispose();
                        }
                    });
                }
            };
            t.start();
            d.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Môn học");
        }

    }//GEN-LAST:event_btnXacNhanThayDoiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JGiaoVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JGiaoVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JGiaoVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JGiaoVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new JGiaoVu(giaovu).setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(JGiaoVu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnTaoMonHoc;
    private javax.swing.JButton btnXacNhanAddSingle;
    private javax.swing.JButton btnXacNhanThayDoi;
    private javax.swing.JButton btnXemMH;
    private javax.swing.JComboBox<String> cbxCMH2;
    private javax.swing.JComboBox<String> cbxCMH3;
    private javax.swing.JComboBox<String> cbxChonMonHoc1;
    private javax.swing.JComboBox<String> cbxDay;
    private javax.swing.JComboBox<String> cbxMonth;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JSpinner spnGBD;
    private javax.swing.JSpinner spnGKT;
    private javax.swing.JSpinner spnPBD;
    private javax.swing.JSpinner spnPKT;
    private javax.swing.JTable tblDiemDanh;
    private javax.swing.JTable tbldssv;
    private javax.swing.JTextField tbxAddHoTenSV;
    private javax.swing.JTextField tbxAddMSSV;
    private javax.swing.JTextField tbxHoVaTenGV;
    private javax.swing.JTextField tbxMaGV;
    private javax.swing.JTextField tbxMaMonHoc;
    private javax.swing.JTextField tbxNgayKetThuc;
    private javax.swing.JTextField tbxPhongHoc;
    private javax.swing.JTextField tbxTenMonHoc;
    private javax.swing.JTextField tbxThuTrongTuan;
    private javax.swing.JTextField tbxYear;
    private javax.swing.JTextField tbxdisplayMH;
    private javax.swing.JTextField tbxdisplayMH2;
    private javax.swing.JTextField tbxdisplayMonHoc3;
    // End of variables declaration//GEN-END:variables
}
