/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainFrame;

import DAO.GiaoVuDAO;
import DAO.HashDAO;
import static DAO.HashDAO.decryp;
import DAO.SinhVienDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import pojo.Giaovu;
import pojo.Sinhvien;

/**
 *
 * @author Gokki
 */
public class JLogin extends javax.swing.JFrame {

    /**
     * Creates new form Login
     *
     * @throws java.lang.ClassNotFoundException
     */
    public JLogin() throws ClassNotFoundException {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(JLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        setLocationRelativeTo(null);
        btnLogin.requestFocus(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGr1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        rabtnSV = new javax.swing.JRadioButton();
        rabtnGV = new javax.swing.JRadioButton();
        tbxUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLoginCancel = new javax.swing.JButton();
        pwfLogin = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chuong Trinh Diem Danh");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(102, 102, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setNextFocusableComponent(btnLogin);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setAutoscrolls(true);
        jPanel2.setNextFocusableComponent(btnLogin);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Mật Khẩu");

        btnLogin.setText("Dang Nhap");
        btnLogin.setFocusCycleRoot(true);
        btnLogin.setNextFocusableComponent(btnLoginCancel);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnGr1.add(rabtnSV);
        rabtnSV.setText("Sinh Vien");

        btnGr1.add(rabtnGV);
        rabtnGV.setSelected(true);
        rabtnGV.setText("Giao Vu");
        rabtnGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rabtnGVActionPerformed(evt);
            }
        });

        tbxUsername.setText("GV001");
        tbxUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxUsernameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Mã Đăng Nhập");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Loại Tài Khoản");

        btnLoginCancel.setText("Thoat");
        btnLoginCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginCancelActionPerformed(evt);
            }
        });

        pwfLogin.setText("tdquangfit");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnLogin)
                        .addGap(18, 18, 18)
                        .addComponent(btnLoginCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tbxUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rabtnSV, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rabtnGV, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pwfLogin))))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbxUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pwfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rabtnSV)
                    .addComponent(rabtnGV))
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnLoginCancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Help");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Help");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbxUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbxUsernameActionPerformed


    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        if (tbxUsername.getText().isEmpty() || pwfLogin.getText().isEmpty()) { // kiểm tra trường dữ liệu không được rỗng
            JOptionPane.showMessageDialog(this, "Tên đăng nhập hoặc mật khẩu không được bỏ trống");
            return;
        } else { // đã điển đủ thông tin đăng nhập

            if (rabtnGV.isSelected()) { // là loại tài khoản Giáo Vụ
                String MaGV = tbxUsername.getText(); // lấy mã giáo vụ
                String pass = pwfLogin.getText(); //lấy mật khẩu
//                pass = HashDAO.encryp(pass, 3);
                Giaovu gv = GiaoVuDAO.GetGiaoVuByMaGV(MaGV); // kiểm tra xem có tài khoản dưới csdl không
                if (gv != null) { // có
                    if (gv.getPassword().compareTo(pass) != 0) {
                        JOptionPane.showMessageDialog(this, "Mật khẩu hoặc tên đăng nhập không đúng. Xin kiểm tra lại");
                    } else {
                        JGiaoVu jgv = null;
                        try {
                            this.setVisible(false);
                            jgv = new JGiaoVu(gv);
                            jgv.setVisible(true);
                            jgv.show(true);
                        } catch (ClassNotFoundException ex) {
                            Logger.getLogger(JLogin.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }

                } else if (MaGV.compareTo("GV001") == 0 && pass.compareTo("tdquangfit") == 0) {
                    JGiaoVu jgv = null;
                    try {
                        this.setVisible(false);
                        jgv = new JGiaoVu(gv);
                        jgv.setVisible(true);
                        jgv.show(true);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(JLogin.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Không tìm thấy tài khoản, xin thử lại");
                }
            } else if (rabtnSV.isSelected()) { // nếu tài khoản đăng nhập là của Sinh Viên
                String MSSV = tbxUsername.getText(); // lấy MSSV và kiểm tra tài khoản đã đăng nhập lần nào chưa
                String Pass = pwfLogin.getText();

                Sinhvien sv = SinhVienDAO.getSinhVienByMSSV(MSSV);
                if (sv == null || sv.getPassword() == null) { // đăng nhập lần đầu, bắt đổi mật khẩu
                    if (MSSV.compareTo(Pass) == 0) {
                        JOptionPane.showMessageDialog(this, "Đây là lần đầu bạn đăng nhập, vui lòng đổi mật khẩu");
                        if (sv == null) { // nếu là một sinh viên mới
                            sv = new Sinhvien(MSSV, Pass);
                            DlgDoiMatKhauSinhVien dmk = new DlgDoiMatKhauSinhVien(this, true, sv);
                            dmk.setLocationRelativeTo(null);
                            dmk.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
                            dmk.setVisible(true);
                            boolean kq = SinhVienDAO.SaveNewSinhVien(sv);
                            if (kq) {
                                JOptionPane.showMessageDialog(this, "Đã cập nhật sinh viên mới");
                                this.setVisible(false);
                                try {
                                    JSinhVien jsv = new JSinhVien(sv);
                                    jsv.setLocationRelativeTo(null);
                                    jsv.setVisible(true);
                                } catch (ClassNotFoundException ex) {
                                    Logger.getLogger(JLogin.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            } else {
                                JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
                            }
                        } else { // nếu sinh viên đã có trong danh sách nhưng đăng nhập lần đầu
                            DlgDoiMatKhauSinhVien dmk = new DlgDoiMatKhauSinhVien(this, true, sv);
                            dmk.setLocationRelativeTo(null);
                            dmk.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
                            dmk.setVisible(true);
                            boolean kq = SinhVienDAO.UpdateSinhVien(sv);
                            if (kq) {
                                JOptionPane.showMessageDialog(this, "Đã cập nhật sinh viên thành công");
                                this.setVisible(false);
                                try {
                                    JSinhVien jsv = new JSinhVien(sv);
                                    jsv.setLocationRelativeTo(null);
                                    jsv.setVisible(true);
                                } catch (ClassNotFoundException ex) {
                                    Logger.getLogger(JLogin.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            } else {
                                JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
                            }
                        }

                    } else {
                        JOptionPane.showMessageDialog(this, "Xin Kiểm tra lại mật khẩu mặc định (Help)");
                    }
                } else { // nếu đã có tài khoản
                    String t = HashDAO.encryp(pwfLogin.getText(), 3);
                    if (sv.getPassword().compareTo(t) != 0) {
                        JOptionPane.showMessageDialog(this, "Mật khẩu hoặc tên đăng nhập không đúng. Xin kiểm tra lại");
                    } else {
                        this.setVisible(false);
                        try {
                            JSinhVien jsv = new JSinhVien(sv);
                            jsv.setLocationRelativeTo(null);
                            jsv.setVisible(true);
                        } catch (ClassNotFoundException ex) {
                            Logger.getLogger(JLogin.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }

            } else { // chưa tick chọn loại tài khoản đăng nhập
                JOptionPane.showMessageDialog(this, "Xin chọn loại tài khoản");
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed


    private void btnLoginCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginCancelActionPerformed
        System.exit(0);
        this.dispose();
    }//GEN-LAST:event_btnLoginCancelActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        DlgHelpLogin dhl = new DlgHelpLogin(this, true);
        dhl.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void rabtnGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rabtnGVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rabtnGVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new JLogin().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(JLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGr1;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLoginCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField pwfLogin;
    private javax.swing.JRadioButton rabtnGV;
    private javax.swing.JRadioButton rabtnSV;
    private javax.swing.JTextField tbxUsername;
    // End of variables declaration//GEN-END:variables
}
